compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@commitlint/types@*":
    dependencies:
      conventional-commits-parser: ^5.0.0

yarnPath: .yarn/releases/yarn-4.4.1.cjs
