name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, test, and build
        run: |
          yarn install --immutable
          yarn lint:ci
          yarn test:ci
        env:
          CI: true
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./artifacts/coverage/lcov.info
          flags: unittest

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Repo Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: yarn install, test, and build
        run: |
          yarn install --immutable
          yarn build
        env:
          CI: true
